name: SPFx PROD Release

on:
  workflow_run:
    workflows: ["SPFx DEV Build"]
    types:
      - completed

jobs:
  prod-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download DEV artifact
        uses: actions/download-artifact@v4
        with:
          name: spfx-dev-package
          # run-id is optional; if omitted, it downloads the latest successful run automatically

      - name: Verify artifact
        run: dir

      - name: Move artifact to root
        run: move spfx-dev-package\*.sppkg .

      - name: Upload PROD artifact
        uses: actions/upload-artifact@v4
        with:
          name: spfx-prod-package
          path: "*.sppkg"
