name: SPFx PROD Release

on:
  workflow_run:
    workflows: ["SPFx DEV Build"]
    types:
      - completed

jobs:
  prod-release:
    runs-on: windows-latest
    environment: prod

    steps:
      - name: Download DEV artifact
        uses: actions/download-artifact@v4
        with:
          name: spfx-dev-package

      - name: Verify package
        run: dir

      - name: Upload PROD artifact
        uses: actions/upload-artifact@v4
        with:
          name: spfx-prod-package
          path: "*.sppkg"
