name: SPFx PROD Release

on:
  workflow_run:
    workflows: ["SPFx DEV Build"]
    types:
      - completed

jobs:
  prod-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    environment: prod

    steps:
      - name: Deploy/Upload PROD artifact
        uses: actions/upload-artifact@v4
        with:
          name: spfx-dev-package
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verify artifact
        run: dir

      - name: Deploy/Upload PROD artifact
        uses: actions/upload-artifact@v4
        with:
          name: spfx-prod-package
          path: "*.sppkg"
